# Some advice on this configuration was taken from:
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?

# TODO specify exact versions on which it has to work

# Generic language, because we prefer to handle C++ configuration ourselves
language: generic

dist: trusty

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &deps
      - libboost-all-dev
      - libhdf5-serial-dev
  
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - *sources
          packages:
            - *deps
            - gcc-5
            - g++-5
      env: 
        - CC='gcc-5'
        - CXX='g++-5'
        - OMP_NUM_THREADS=4
      
    - compiler: clang
      addons:
        apt:
          sources:
            - *sources
          packages:
            - *deps
            - clang-3.8
      env: 
        - CC='clang-3.8'
        - CXX='clang++-3.8'
        - OMP_NUM_THREADS=4

before_install:
  - cmake .
  - make

script:
  - ./travis.sh

notifications:
  email: false
