# TODO specify exact versions on which it has to work
language: cpp
script: ./some_tests --gtest_output=xml  # writes details to test_detail.xml
os:
  - linux
  #- osx
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-5
      - g++-5
      - libboost-all-dev
      - libhdf5-serial-dev

# Some advice on this configuration was taken from:
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?

env: 
  - CXX=g++-5
    OMP_NUM_THREADS=4

matrix:
  include:
    - addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-3.8
            - libboost-all-dev
            - libhdf5-serial-dev
      env: 
        - CXX=clang++-3.8
          OMP_NUM_THREADS=4

before_install:
  - cmake .
  - make

notifications:
  email: false
