# Some advice on this configuration was taken from:
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?

# TODO specify exact versions on which it has to work

language: cpp

dist: trusty

addons:
  apt:
    packages:
      - libboost-all-dev
      - libhdf5-serial-dev
  
matrix:
  include:
    - compiler: gcc
      addons:
      apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
          - gcc-5
          - g++-5
      env: 
          - CXX=g++-5
          - OMP_NUM_THREADS=4
      
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-3.8
      env: 
        - CXX=clang++-3.8
        - OMP_NUM_THREADS=4

before_install:
  - cmake .
  - make
  
script:
  - ./travis.sh

notifications:
  email: false
