# Some advice on this configuration was taken from:
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?

# TODO specify exact versions on which it has to work

language: cpp

dist: trusty

addons:
  apt:
    packages: &default_packages
      - libboost-all-dev
      - libhdf5-serial-dev
  
matrix:
  include:
    - compiler: gcc
      addons:
      apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - *default_packages
            - gcc-5
            - g++-5
      env: 
        - CC_COMPILER_NAME='gcc-5'
        - CXX_COMPILER_NAME='g++-5'
        - OMP_NUM_THREADS=4
      
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - *default_packages
            - clang-3.8
      env: 
        - CC_COMPILER_NAME='clang-3.8'
        - CXX_COMPILER_NAME='clang++-3.8'
        - OMP_NUM_THREADS=4

before_install:
  - cmake .
  - make
  
script:
  - ./travis.sh

notifications:
  email: false
