# TODO specify exact versions on which it has to work
language: cpp
os:
  - linux
  #- osx
dist: trusty
sudo: required

# Some advice on this configuration was taken from:
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?

addons:
  apt:
    packages:
      - libboost-all-dev
      - libhdf5-serial-dev
  
matrix:
  include:
    - compiler: gcc
      addons:
      apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
          - gcc-5
          - g++-5
      env: 
          - CXX=g++-5
          - OMP_NUM_THREADS=4
      
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-3.8
      env: 
        - CXX=clang++-3.8
        - OMP_NUM_THREADS=4

script:
  # writes xml details to test_detail.xml, output to gtest_output.txt
  - ./some_tests --gtest_output=xml --gtest_color=yes > gtest_output.txt 2>&1

after_script:
  - ./print-gtest.py test_detail.xml
  - cat gtest_output.txt
  
before_install:
  - cmake .
  - make

notifications:
  email: false
